### ISSUE TITLE
on x64 platfrom dynamic_database_producer will get worng "create_database"

### ISSUE THREAD

**Issue by von500** [zussel/oos#53]
// get create function
  create_ = reinterpret_cast<create_func>(reinterpret_cast<long>(loader_.function("create_database")));
  // get destroy function
  destroy_ = reinterpret_cast<destroy_func>(reinterpret_cast<long>(loader_.function("destroy_database")));

the "long" type is to small for x64 platfrom

**Comment by zussel** [comment]
That's right! Thanks for the hint. I'll prepare a hotfix release with a fix for it.

BTW: Do you use it under windows or linux?

**Comment by von500** [comment]
windows , with MSSQL,  for get select results you can use SQLMoreResults when execute stored procedure

**Comment by von500** [comment]
when use "{?= CALL}" ,we can't get the retuan result. there no SQL_PARAM_OUTPUT bind Parameter and ther is no methon to get the result. also the inout param.

**Comment by zussel** [comment]
Thanks for your reply. By I made a hotfix branch (hotfix/dlsym) which fixes the the function cast. If you need the fix now, just ckeck out the branch and build the library.

Can you provide some lines of code outlining your use case for your last two comments?

**Comment by von500** [comment]
bool mssql_result::fetch()
{
  SQLRETURN ret = SQLFetch(stmt_);
  if (SQL_SUCCEEDED(ret)) {
    return true;
  }
  else {
	  ret = SQLMoreResults(stmt_);
	  if (SQL_NO_DATA == ret)
	  {
		  return false;
	  }else
	  if (SQL_SUCCEEDED(ret)) {
		  return fetch();
	  }
    throw_error(ret, SQL_HANDLE_STMT, stmt_, "mssql", "error on fetching next row");
    return true;
  }
}

I can't get the return result from stored procedure.
