### ISSUE TITLE
how to remove one record from table

### ISSUE THREAD

**Issue by dmcyang163** [zussel/oos#54]
id  name 
1   tom
2   jacky
3   tom
...   ...

if  i want to delete the recode where name=tom,
any suggestion or  sample code？

**Comment by zussel** [comment]
Hi,

thanks for your question! I assume you use the current version 0.2.1 and you're dealing with objects wrapped in the recommended object_ptr.

In short: Just open a view, filter your objects and remove each filtered object from object_store
Example (assuming the entity/table is called person)

```cpp
// some shortcuts
typedef oos::object_view<person> person_view_t;
typedef oos::object_ptr<person> person_ptr;
typedef person_view_t::iterator iterator;
person_view_t pview(ostore);

// container for object to delete
std::vector<person_ptr> persons;

// object collector function
void collect(const person_ptr &p) {
  persons.push_back(p);
}

// declare a variable/literal for the name
oos::variable<std::string> x(oos::make_var(&person::name));
std::string name("tom");

// use the for_each_if function
for_each_if(pview.begin(), pview.end(), x == name, collect);

// delete found objects
while (!persons.empty()) {
  person_ptr p = persons.back();
  persons.pop_back();
  ostore.remove(p);
}
```

Hope there are no typos but that's the way to delete objects in version 0.2.1.

If you're not satisfied with the solution or things are unclear just give me a not.

Currently I'm preparing a new release (0.5) where a lot will change (no root object for your entities, a fluent query interface, an orm layer). Just take a look on the develop branch. Unfortunately the documentation for the next release isn't finished yet.

**Comment by dmcyang163** [comment]
thank you very much， i will get a try

**Comment by dmcyang163** [comment]
unfortunately，here is the error

terminate called after throwing an instance of 'std::runtime_error'
  what():  couldn't fínd library [root]
dlopen error: liboos-root.so: cannot open shared object file: No such file or directoryAborted

**Comment by dmcyang163** [comment]
build 0.21 have no liboos-root.so

**Comment by zussel** [comment]
The `liboos-root.so` is a dynamic build name, where `root` is the database backend key. There are currently three supported backends:
- sqlite
- mysql
- mssql

How did you create the session. It must look something like that (where `sqlite` could also be `mysql` or `mssql`):

`oos::session db(ostore, "sqlite://person.db");`

Can you check it and my be post the code which din't work?

**Comment by dmcyang163** [comment]
i use mysql 
oos::session db(ostore, "root:tom123@127.0.0.1/test");
as on_open function tip 
// parse user[:passwd]@host/db

**Comment by dmcyang163** [comment]
copy the code from doc/web as a test
void ooshelper::Insert()
{
	/*
	* create an object store
	* and insert a prototype for
	* our person class
	*/
	oos::object_store ostore;
	ostore.insert_prototype<person>("person");

	oos::session db(ostore, "root:tom123@127.0.0.1/test");
	db.create();


	typedef oos::object_ptr<person> person_ptr;
	person_ptr p = db.insert(new person("Theo"));

	/*
	 * insert several objects using
	 * a transaction.
	 *
	 * after starting the transaction
	 * use the object store to insert
	 * objects
	 */
	oos::transaction tr(db);

	// start transaction
	try {
		tr.begin();

		ostore.insert(new person("George"));
		ostore.insert(new person("Jane"));
		ostore.insert(new person("Tim"));
		ostore.insert(new person("Walter"));

		tr.commit();
	} catch (std::exception&) {
		// an error occurred: do rollback
		tr.rollback();
	}

	/*
	 * to access the objects one
	 * have to open a view over
	 * the requested object type
	 *
	 * then one can iterate over the
	 * view and access or modify the
	 * objects
	 */
	typedef oos::object_ptr<person> person_ptr;
	typedef oos::object_view<person> person_view_t;

	person_view_t oview(ostore);

	person_view_t::iterator i = oview.begin();
	person_view_t::iterator last = oview.end();
	for (; i != last; ++i) {
		person_ptr p = *i;
		std::cout << "person: " << p->name() << "\n";
	}
}

**Comment by zussel** [comment]
Thanks for the code. The example code is a good point to start!

As I assumed the connection string is not correct:

`oos::session db(ostore, "root:tom123@127.0.0.1/test");`

The database identifier (`sqlite`, `mysql` or `mssql`) is missing.

If you use MySQL change the line like this:

`oos::session db(ostore, "mysql://root:tom123@127.0.0.1/test");`

And it should work.

I'll add a check on the database identifier (with a appropriate error message) in the next version of the library.

**Comment by dmcyang163** [comment]
thank you very much for give me a hand，
i try 
oos::session db(ostore, "mysql://root:tom123@127.0.0.1/test");

then， the error as follow 
terminate called after throwing an instance of 'std::runtime_error'
  what():  couldn't fínd library [mysql]
dlopen error: liboos-mysql.so: cannot open shared object file: No such file or directoryAborted

**Comment by zussel** [comment]
Looks like the program couldn't find the mysql backend library.

How did you install OOS? Or did you compile it by hand?

When compiling the library by yourself than you must have the mysql development libraries installed, so that the build system can find them.

You can also use the tar.gz package provided on the [release page](https://github.com/zussel/oos/releases/tag/v0.2.1).

**Comment by dmcyang163** [comment]
as you say i forgot to install libmysql++-dev
this:
sudo apt-get install libmysql++-dev

Thank you so much for helping me out today

**Comment by zussel** [comment]
You're welcome. Hope you've fun with my lib. Watch out for the next release.
