### ISSUE TITLE
Install script errors

### ISSUE THREAD

**Issue by saki7** [zussel/oos#55]
Hi there,

I'm new to OOS and I'm very much looking forward to getting in!
I've found some errors in the install script `lib/src/CMakeLists.txt` - the command `make install` fails.

Suggestions / Questions:
- `${PROJECT_SOURCE_DIR}/include` should be replaced by `${PROJECT_SOURCE_DIR}/lib/include`?
- `object/serializable.hpp` and some files seem to be missing/replaced by another. Maybe just remove it from the install script, or add the another file (which is perhaps introduced into the develop branch)? For this file, I see 2 same entries in the file by the way.
- `object/object_container.hpp` `object/object_list.hpp` `object/object_vector.hpp` `object/linked_object_list.hpp` `object/object_atomizer.hpp` `object/identifier.hpp` `object/primary_key_writer.hpp` - Same as above.
- JSON - entire feature seems to be missing. Obsoleted maybe?

Thanks -
Nana

**Comment by zussel** [comment]
Hi Nana,

thanks for your message. It's cool there is some interest in my library!

It seems you checked the current development branch which is in heavy development right now. The documentation fits to the current master (version 0.2,1). So you're right JSON was completely removed. I just wanted to concentrate on the main features (a fluent sql query interface and no base class for the stored objects).

That takes me to your suggestions concerning CMakeLists.txt and missing files. I'll fix these errors as soon possible (Right now I'm fixing some mssql backend things).

If you wanna start and give OOS a try, I recomment to check out the master branch/release 0.2.1. I hope I can release the version 0.5 soon ('m almost done with my issues).

Sascha

**Comment by saki7** [comment]
I think this is done
