### ISSUE TITLE
General question: how to use persistence, session, connection and query

### ISSUE THREAD

**Issue by saki7** [zussel/oos#56]
Hi there,

I've been playing around in the develop branch :) for a while and I have some questions.
I've looked into the test codes, and I see three classes to deal with connection: `persistence`, `session` and `connection`.

It looks like you open a connection by the `persistence` using the `dns_` and create a session with `session`, then `s.insert()` some stuff. Is this the correct way to modify the database?

For querying, it seems like you open a `connection` using the `dns_` and `c.open()` it, add queries then `.execute(c)`;

So here are my questions:
- In the first place, what's the difference between `session` and `connection`? It looks like they are just each separated for modifying/querying purposes only.
- Is the `persistence` object ever needed for querying?
- Let's say I have a daemon written in C++ which fetches/stores objects into the database. *The daemon will be running for a long period of time*, for like > 1 week. Isn't it gonna consume unnecessary resources if you repeatedly open up a `connection` (then close it when you're done) when you are querying? Is it a *good* way to have a VERY long persistence in active (if it's possible)?
- What's the best way to "open up a connection" and query/modify the db in the short period of time? Just use the `persistence` / `session` for modifying and `connection` for querying?

Thanks in advance - looking forward to receiving your reply,
Nana

**Comment by zussel** [comment]
Hi,

I think you should take a look at the corresponding documentation for the development branch. Just checkout the [gh-pages-new](https://github.com/zussel/oos/tree/gh-pages-new) branch, [setup ruby and jekyll](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/) and read the _Getting started_ guide.

In short: There are three main modules in OOS
- The object store
- The SQL fluent query interface
- The ORM Layer

```
+--------------------+------------------+
|                   ORM                 |
+--------------------+------------------+
|  Query Interface   |   Object Store   |
+--------------------+------------------+
```

If you just want to make database queries without ORM functionality just use the query interface ( `sql/query.hpp`). You can use it like

```cpp
connection c("sqlite://db.sqlite");

query<person> q("persion", c);

person p("tom");
q.insert(p);
// ref to name column
column name("name");
auto res = q.select().where(name == "tom").execute();

for (auto p : res) {
  // do something
}
```

If you want a container for all your objects/entities without database (but with transactions) use the object store.

```cpp

object_store store;
store.attach<person>("person");

auto optr = store.insert(new person("Nana"));
```
If you want both, use the ORM layer.

```cpp
persistence p("sqlite://db.sqlite");
p.attach<person>("person");

// create db tables
p.create();

// create a session
session s(p);

// transaction
auto tr = s.begin();
try {
  s.insert(new person("bill"));
  s.insert(new person("ted"));

  tr.commit();
} catch(std::exception &ex) {
  tr.rollback();
}
```

I hope that helps to clarify some things.

Concerning your daemon question you could just open a connection on startup and keep it open until the daemon is terminated.

**Comment by saki7** [comment]
Hi,

Thanks for the quick reply :)
I've checked out the documentation branch but unfortunately I'm afraid there was not enough info I was looking for.

> If you want both, use the ORM layer.

I think.... I need *both* in my case. I want to insert an object with transactions, and then query them using the query interface. So using `persistence` / `session` seems to fit my case.

**But how can I attach the query interface into the `session`?**
`session` has member functions such as `begin()` and `insert()` to modify stuffs, however `select()` returns `object_view<T>`... I was expecting `query<T>` here.

Another way I expected was to pass the `persistence` object to the `query` - but unfortunately `query` only accepts a `connection`.

Therefore, it looks like you need to have both `persistence` and `connection` objects to use the ORM layer to me. Doesn't it result in having two connections at the same time?

Thanks to your reply, I think I've understood better than before but I'm afraid I'm still bit confused. It would be nice if you could help me a little more.

Thanks,
Nana

**Comment by zussel** [comment]
I think you achieve what you want with the ORM layer.

In the ORM layer all objects are stored (cached) in the object_store.

```cpp
session s(p);

s.insert(new person("jane");
```

In the example above the new person is inserted into the database and 'cached' in the object store hidden in the persistence object.

A call to `session::select()` returns indeed an `object_view<T>` of the desired type. And this view represents the database table hence all objects.

If you want to filter the view (the selection) you can use expressions (see the [expression.md](https://github.com/zussel/oos/blob/gh-pages-new/docs/expressions.md) file in the doc).

```cpp
auto view = s.select<person>();
oos::variable<int> x(oos::make_var(&person::age));

// find first person with age 25
auto i = view.find_if(x == 25);
```
But you're right the call to select should be equal to query select. I'll create an issue on that.

I hope I understood your usecase correctly.

**Comment by saki7** [comment]
Yeah, the 'filtering' of `object_view<T>` indeed is a nice feature.

> But you're right the call to select should be equal to query select. I'll create an issue on that.

That's what I was thinking of. Thanks to you that you understood my concerns.

But wait, `query<T>`'s `execute()` returns `result<T>`.
If you're going to make the `session::select()` call equal to that of `query<T>`, where does `object_view<T>` go then?

Since `result<T>` is just a tiny wrapper for the row, is it possible to make `result<T>` obsoleted and make the `execute()` function return `object_view<T>` instead?
Then I think the client-side 'filtering' feature will also be available even *after* querying.

**Comment by zussel** [comment]
From the layering (ORM on top of object store and query interface) I can't mix `object_view<T>` into the query module. They intent to be separated. Therefor `query<T>::execute()` will return `result<T>` because it is the direct connection to the underlying backend fetch function. So `result<T>` provides a `std::forward_iterator`.

But what I was thinking of is to give `object_view<T>` an equal fluent interface as `query<T>` has.

So with your quote

> Just one complex query per search plus multiple client-side filtering is the good way

you're right.

If you use only the ORM layer the querying is hidden in a table object and you deal with `object_view<T>` and its filtering.

**Comment by saki7** [comment]
> But what I was thinking of is to give object_view<T> an equal fluent interface as query<T> has.

Won't it result in a 'greedy' loading which loads the entire rows on calling `session::select()`?
I think `session::select()` needs to just add the `SELECT` statement to the session, with no instant loading.
Yielding `object_view<T>` results in greedy loading, doesn't it?

Filtering is a different issue here; I think `session::select()` must only yield a cached SQL statement, then 'execute' it to publish the composed SQL statement, and then finally make the user to be able to filter them client-side IMO.

**Comment by zussel** [comment]
That is the intention behind filtering a `object_view<T>`. Data is already loaded, with the ability to filter it.

And I think that I'll keep the `object_view<T>` filtering with expressions (which a quiet similar to `query<T>::where` conditions).

So I should get the release done soon (hopefully by the end of year at leat in January).

**Comment by saki7** [comment]
> Data is already loaded, with the ability to filter it.

Just curious, why wouldn't you make `object_view<T>` capable of lazy loading (like described in the roadmap)?

I understand it's nice to have `object_view<T>` kept having expressions to filter with, but, loading the whole table regardless of queries provided seems like a bad idea to me.

Isn't it a good way to provide SQL querying feature for `object_view<T>` available at first and then provide the existing filtering feature of `object_view<T>`?

**Comment by saki7** [comment]
Or... were you thinking of the same thing as my thoughts and I'm totally writing the same thing as you expected?

**Comment by zussel** [comment]
Yes, I was thinking of something similar to your thought :smile:

The idea of the object_store came from a project on which I worked almost 20 years ago. It was a container which loads all entities from database at once. I liked the design but had no idea how it was implemented. So I started with my object_store.

Later I thought, that it would be good to have the ability of lazy loading. That feature will be done in a future version. I like your suggestion of `session::select<T>().where()`. It is good point to start when implementing the lazy loading.

By now (version 0.5) the user is forced to load all data at once. But I think that's ok.

**Comment by saki7** [comment]
Nice, looking forward to seeing future updates :smile: 
Referring to your comment

> But you're right the call to select should be equal to query select. I'll create an issue on that.

And considering recent discussions, I have come into a conclusion: *implement API having equal/fluent interface with `query<T>` and capable of lazy loading*.

I'm quite sure that both can be achieved at the same time since the interface will build up the SQL statement and the lazy loading could be triggered at the point of `execute()`. I'll create an issue and closing this one here...

Thanks for all your comments & support.

**Comment by zussel** [comment]
Thanks for opening the new ticket. I'll comment on it.

This was a very promising discussion. Thanks for your first user experience.
