### ISSUE TITLE
Adding a static member function to determine the table name?

### ISSUE THREAD

**Issue by saki7** [zussel/oos#57]
I think that introducing a "rule" to an object class which requests a user to provide a table name in a static member function can reduce redundancy in certain cases.

An example:

```cpp
class person
{
public:
    static std::string const oos_table() { return "person"; }
};
```

Could probably change the API from:

```cpp
p.attach<person>("person");
```

to this way:

```cpp
p.attach<person>();
```

The function template changes to something like this:

```cpp
class persistence
{
public:
    template<class Object>
    void attach()
    {
        do_something_with_the_table_name(Object::oos_table());
    }
}
```

This is also possible in many cases such as `query`:

```cpp
oos::query<person> q("person"); // before
oos::query<person> q; // after
```

You know, it's a pain to write the table name every single time when you're querying.

I think many Web friendly languages such as Ruby on Rails is doing the same thing in meta-programming.
What do you think about this?

**Comment by zussel** [comment]
I know what you mean. I thought also about this 'problem'. But I came to the conclusion that if you use the ORM layer, you only have to write the name of a table once:

```cpp
p.attach<person>("person");
```

After this is done, you don't need to write it again.

Actually this is a bit different when dealing only with the query interface. Here I can think of an optional setup for entity type to table name relation.

Maybe something like
```cpp
query<person>::bind("person");

// ...

query<person> q; // table name is retrieved from binding above
```

Or this couldn't be done automagically. The mapping is setup when you first write
```cpp
query<person> q("person");
```

Then it is mapped internally and when you use it for second or third time just write
```cpp
query<person> q;
```

I think I'll take this into consideration for the next version.

**Comment by saki7** [comment]
Nice - I think the former way looks more explicit and user-friendly though. I guess many C++ experts do not like stuffs which is done internally.

You can close this issue if you want, or leave it till the implementation is done.

Thanks,
Nana

**Comment by saki7** [comment]
Nicely done
