### ISSUE TITLE
dns parsing: specify port for the connection

### ISSUE THREAD

**Issue by saki7** [zussel/oos#61]
It would be great if we could specify a port for the connection:

https://github.com/zussel/oos/blob/c96f15f3ce81c223924497e3cf86be8ff9874f38/db/mysql/src/mysql_connection.cpp#L77

I'm concerning security issues. I'm afraid that forcing the default port (`0`) might not be suitable for certain production servers.

**Comment by zussel** [comment]
Yes you're right! The parsing and handling of the connection string will be a separate issue for future release. But I'll see if I can add the port into connection string parsing.

P.S.: I'm getting aware that my (one person) project getting bigger.

**Comment by saki7** [comment]
I'd suggest using `std::regex` rather than `std::string::find` and `std::string::substr` - it's more robust and readable than old `std::string` member functions. It should be much easier to implement the dns parsing.

I'll send a pull request on this - I hope you'll like it.

**Comment by zussel** [comment]
```std::regex``` should be a good decision. I'm looking forward to your pull request.

**Comment by saki7** [comment]
Done.

**Comment by zussel** [comment]
Are you able to take a look at the regex for gcc4.8? Travis tells us there is a ```regex_error```. There are also some other issues with gcc4.9 I'll take a deeper look on.

**Comment by saki7** [comment]
@zussel See http://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions

**<regex> was implemented and released in GCC 4.9.0.**

We should drop GCC 4.9.0. It's old enough.

**Comment by saki7** [comment]
And as far as I can see the tests for GCC 4.9.0 and above are passing

**Comment by zussel** [comment]
Ahh, now I remember why I used plain ```std::string::find()``` to implement connection string parsing. At time of writing gcc4.8 was the current gcc. So I went to use old style parsing.

Now, I think it's safe to drop support for gcc4.8.

Concerning regex gcc4.9 passes but another test fails. And that's what I'll take a look at.
