### ISSUE TITLE
Escaping & quoting are needed for identifier names

### ISSUE THREAD

**Issue by saki7** [zussel/oos#62]
Currently oos publishes SQL statements like below:

```sql
CREATE TABLE machine (tool1 INTEGER, tool2 INTEGER)
```

This really needs to be

```sql
CREATE TABLE `machine` (`tool1` INTEGER, `tool2` INTEGER)
```

I was very surprised when I saw this. **This should be considered as very high-priority issue** IMHO.

When it comes to relations it becomes more serious:

```cpp
oos::has_many<Books> references;
s.serialize("book_and_book", references, "from", "to");
```

Yields SQL statement like this:

```sql
CREATE TABLE book_and_book (from INTEGER, to INTEGER)
```

Boom! `from` is a reserved keyword in SQL.
This must be

```sql
CREATE TABLE `book_and_book` (`from` INTEGER, `to` INTEGER)
```

---

Same applies to querying, it should be in the same form:

```sql
SELECT `books`.* FROM `books` WHERE `books`.`author` LIKE 'John'
```

```sql
SELECT `book_and_book`.`to` FROM `book_and_book` WHERE `book_and_book`.`from` = `12`
```

@zussel Can you take a look into this?

**Comment by saki7** [comment]
Due to my investigation I think all the places which directly use `oos::detail::tablename` and `oos::column::name` should be replaced with `oos::escape_token(col.name)` and `oos::escape_token(table.tab)` respectively...


Naive example here (untested but should work in most cases. Need your opinion)

```cpp
inline std::string escape_token(const std::string &token)
{
    return "`" + token + "`";
}
```

Related codes those might be affected seems mostly located in `basic_dialect_linker.cpp` but not sure if there's other places which uses the values directly.

**Comment by zussel** [comment]
Thank you very much for your investigations! Learning never stops. I wasn't aware of this behavior. I'll take your suggestion and integrate escaping into the release.

Shouldn't be that complicated but obviously with great impact.

**Comment by zussel** [comment]
After a short research I found out that there is a common quote symbol in SQl-99 but the default behavior of the sql server, mysql and sqllite is different.

See [here](http://stackoverflow.com/a/2901499/1545267) and [here](http://stackoverflow.com/a/2901502/1545267).

So I have at least to set the start and end quote character for all oos backends or provide a virtual method in `connection_impl.hpp`

**Comment by saki7** [comment]
Thanks for your reply, I'm very much looking forward to seeing the fix.

There seems like `mysql_real_escape_string()` for MySQL - and there must be corresponding ones for mssql and SQLite too.

Btw, how about BLOB variables? Looking into the test codes, BLOB data type looks not supported for now. And I think the escaping will also be required for the blob data. I've saw in some places that you must first convert the data into hex values and then unhex() it when inserting, but I'm afraid I'm not sure how it works actually (sorry I'm not familiar with handling BLOBs).

Can't wait for the fix - it's kinda show-stopper for my project. Ask me anything if you need any help.

**Comment by zussel** [comment]
I hope I can provide the fix by the weekend (you know I'm a father of two... :smile:)

Thanks for the hint of ```mysql_real_escape_string()```. I'll find the functions for the other to backends and start the fix.

Blob is also an issue. I made some expierence with mssql and ```TEXT``` datatype. But yeah there is a lot todo.

Nice to here that you've started a project! That's a good motivation to getting things done.

**Comment by saki7** [comment]
Sorry `mysql_real_escape_string()` was for *string literals* - not for *identifiers*. Therefore it does not escape the quote (= backtick in MySQL context).

So it should be good to use for updating string columns - such as VARCHAR and TEXT.

After some googling, my solution for escaping *identifiers* are to simply manually escape them by replacing the quote with escaped quotes (backtick => double-backtick in MySQL context). Then surround them with quotes as I explained above.

**Comment by zussel** [comment]
I started this feature with a feature branch ```feature/escaping```.

There is a test in ```QueryTestUnit::test_quoted_columns()```.

I encountered a design problem when using where clauses. I've to change the API in the condition classes to escape the column names in where clauses. It's not a big thing but I've to do it.

Beside of that escaping works fine.

**Comment by saki7** [comment]
👍 👍 👍 I have looked into the branch and have these suggestions so far:

- I think it's more appropriate to change the name of the current test `QueryTestUnit::test_quoted_columns()` to `QueryTestUnit::test_quoted_keywords` or something since the test itself is not actually testing against "quoted columns", it's actually testing if the reserved keywords have been properly quoted or not.
- Hence the current test name looks quite ambiguous and hard to distinguish it from an another test which tests against columns having names such as `[country]` - which obviously looks like a "quoted column".
- I think the current code (not the test code, I mean the implementation code) is just "quoting" the identifiers; not "escaping" them internally.
- So we must have to improve `basic_dialect_linker::quote_string()` to "replace the quotes inside the identifiers" i.e. `[country]` -> `[[country]` and add a corresponding test, which in this case should be named `QueryTestUnit::test_quoted_columns()`, or, to be more specific, `QueryTestUnit::test_columns_with_quotes_in_name()`
- **Note that in MSSQL the closing bracket has its special meaning only if combined with the corresponding opening bracket, so you don't need to escape it as far as you escape the opening bracket.**
- **In MySQL context it's different since the quotes are the same character - which is backtick - so you need to escape both of them.**
- If you feel the need to test against **every names in OOS context**, I think we could extract `basic_dialect_linker::quote_string()` only and input some evil data into it to make sure everything is both quoted **AND** escaped.

Thanks for reading, I hope you understand my idea.

**Comment by zussel** [comment]
Thanks for your suggestions! I've already renamed the test into ```test_quoted_identifier```.

There will be a second test concerning escaping quote characters. I know I missed this behavior with the current implementation. But I'll implement this in ```basic_dialect_linker``` and add the required test. I like the name ```test_columns_with_quotes_in_name()```. So watch out for a test with that name!

**Comment by saki7** [comment]
I've read your codes so far - very nice 👍 

I'm not sure if you like it or not but I have come out of one more suggestion now; I think it's better to change the name of current function `quote_string()` to `quote_identifier()`. Using the term "string" is pretty ambiguous in SQL query context IMHO. And we also need to reserve the name `quote_string_literal()` for quoting string literals which internally uses the SQL drivers' escape API (the one I mentioned; `mysql_real_escape_string()` in MySQL). Should be implemented in virtual method too.

**Comment by zussel** [comment]
So I think feature is almost finished. Last thing is that strings like ```COUNT(*)``` are also quoted. But that's not a big thing.

I hope I didn't miss a thing.

**Comment by saki7** [comment]
Do you want to keep the whole escaping feature including escaping **string literals** in this issue or should we split the issue?

The remaining feature includes
- Escaping string literals
- Make sure the escaping of identifiers and string literals don't be mixed up
- Adding tests for it

**Comment by zussel** [comment]
I want to Split it up. This Feature is Just about quoting and escaping identifiers.

I'll implementiert escaping String literals in another Feature.

Blobs are so far not supported. That's an issue for the next Release.

Is that ok for you?

**Comment by zussel** [comment]
Oh, I think I've read over your post with the test suggestions. Sorry for that!

I'll prepare a test covering all your mentioned test cases. I think my implementation should cover all. But w'll see.

I wasn't aware about the ```size_t``` and ```std::size_t``` thing. Good hint. I'll replace all ```size_t``` occurrences.

**Comment by saki7** [comment]
Since the last release was almost 3 years ago - it's nice to have Floian available sooner. No more new features are needed for Florian I think. So leaving blobs for the next release is ok for me.

Can you triage all remaining tickets I opened and add milestones/labels to them?

**Comment by saki7** [comment]
I'm afraid that the current implementation of `basic_dialect::escape_quotes_in_identifier()` is wrong. It now replaces open_char to open_char+open_char which appears to work in MySQL but does not work in MSSQL.

- open_char evaluates to `[`
- All occurrences of `[` are replaced into `[[`
- If my understandings are correct, the opening bracket should not be escaped in MSSQL
- You will get an extra `[` character for the escaped identifier name

And you can also consider adding `const` to open_char and close_char

**Comment by saki7** [comment]
And also the line

```cpp
 if (open_char != close_char) {
```

is not logically correct. I think the statement should contain the dialect's context within:

```cpp
if (dialect()->identifier_escape_type() /* virtual method */ == oss::dialect_traits::Escaping::ESCAPE_CLOSING_BRACKET) {
```

Something like the code above might give you an idea.

**Comment by zussel** [comment]
Ok, it was late last night :smile:

I thought I had to replace both characters for MSSQL, but maybe I understood it wrong. I'll double check it.

Good suggestion of ```identifier_escape_type()``` method. I'll take that into account!

Yes, I saw that SQLite has several types of quote identifiers. I'll figure out how this can fit into the implementation.

Thanks for your suggestions!

**Comment by zussel** [comment]
I think I finished this feature. I merged it into develop. You're welcome to have a look at it.

**Comment by saki7** [comment]
So you've decided to choose `"the double quotes"` (which is done by fallbacking to basic_dialect) to escape the identifier in SQLite. I think it's fine since when the double quote appears at first, other identifiers will be ignored until the closing double quote appears. So the implementation looks fine.

Btw it would be nice if you could self-pull-request the feature/bugfix branch for us before merging. I want to see the CI stats.

Nicely done, thanks for your hard effort.

**Comment by zussel** [comment]
Yes I've decided to go for double quotes for SQLite. Because as I understand there documentation they use double quotes in the first place and backticks and square braces only for compatibility. So double quotes will fit our need.

The self-pull-request is a good hint. As long as I'm alone writing my library it was ok to just finish the feature branch. But the more contributors/developers are working on it, this will lead to better quality and transparency!
