### ISSUE TITLE
Community: Launch a Gitter

### ISSUE THREAD

**Issue by saki7** [zussel/oos#68]
Gitter - https://gitter.im/

Pros
- It's trusted & used by many open source projects & enterprise company
- We can have more casual talking (which is very nice 😄 ) (but when it's done on GitHub, it makes the issue log messy)
- We can help newcomers asking simple questions like #54 and #56 in probably **fast** response
  - They are **questions**, not **issues** actually. So it should be done in other places than the issue tracker. In old times they used mailing lists, nowadays realtime chat is suitable.
- We can ask really simple questions related to the C++ language or the OOS API - like "how to insert duplicate keys into a map?" or "how does this API implementation work?"
- We might prevent creation of "Suggestions" which may cause the flooding of issue tracker
  - I really want to make this (I mean *this* issue) kind of suggestions done in **chat**, not in **issue** context.

Cons
- We really need to make sure to feedback the things decided in Gitter into GitHub (quote the log into the issue, etc...)
  - Or it could lead to "closed community" which kills all pros shown above

@zussel What do you think of this suggestion?

**Comment by zussel** [comment]
I thought about something like this as well. But wanted to wait until 0.5.0 is released. Gitter is also my first choice. But indeed it can end up in a lot of "_support_" (what's actually a good sign - although I started writing this library just for my needs I was wondering if the community needs something like this).

My plan was to introduce Gitter with the release of 0.5.0 and its new project/documentation. That will keep us focused on the release until its done.

What do you think!

**Comment by saki7** [comment]
> But indeed it can end up in a lot of "support" (what's actually a good sign

Indeed.

> I started writing this library just for my needs I was wondering if the community needs something like this

So far this library's got 30 stars so you can be proud of it. I'm planning to contribute with more PRs. Let's see if we could reach 200 stars in 2017.
I've took a lot of time for researching similar libraries but most of them was way far from "modern code".

And sure, we can introduce Gitter with the release of 0.5.0. No need to hurry for this one.

**Comment by zussel** [comment]
Nice to hear that you'd like to contribute more PRs! I'm looking forward to. I think it helps to have an unbiased opinion concerning OOS. Actually it helped the last two weeks!

200 stars in 2017 would be a dream. But when releasing 0.5.0 I'm thinking to use also the twitter channel to draw some interest upon the library. And if we provide an easy "getting started" some more simple people will give OOS a try. W'll see...

**Comment by zussel** [comment]
I've created a [gitter](https://gitter.im/oos-orm/).

**Comment by saki7** [comment]
I've joined it!

**Comment by saki7** [comment]
The next steps will be adding Gitter link to the documentation and GitHub `README.md`

**Comment by zussel** [comment]
Linked in README.md
