### ISSUE TITLE
Implement belongs_to and has_and_belongs_to_many

### ISSUE THREAD

**Issue by saki7** [zussel/oos#74]
Quoting from #71:

>> one_to_one isn't explicitly supported, you can achieve it with having a has_one attribute within each entity. But its not exactly what one_to_one stands for.

> I'm afraid that has_one + has_one is logically incorrect.
> The possible scenarios are only limited to following:

> - has_one + belongs_to = "Game has one Game Community, Game Community belongs to one Game"
> - has_many + belongs_to = "Post has many Attachments, Attachment belongs to one Post"
> - has_many + has_many = "Post has many Categories, Category has many Posts" (need a joining table)

For OOS 0.5.1.

**Comment by zussel** [comment]
Btw: Good summary about the relationships!

By now only ```has_many``` with no counterpart ist implemented :disappointed:

But w'll change that!

**Comment by zussel** [comment]
I came to the conclusion that at least ```belongs_to``` is a major feature that shouldn't be missing. Therefor I attached it to milestone 0.5.0.
